Fix yq commands for yq version 4.25 (-r is not supported)
In run_robot_test.sh we called yq -er, but after upgrading to latest
yq version 4.25, it is not supported (and can break the script):
```
$ yq --version
yq (https://github.com/mikefarah/yq/) version 4.25.1
$ yq -r
Error: unknown shorthand flag: 'r' in -r
```

Signed-off-by: manosnoam <nmanos@redhat.com>